//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectSARS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALA()
        {
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public int IDSALA { get; set; }
        public Nullable<int> ID_UBICACION { get; set; }
        public string IDCOORD { get; set; }
        public string NOMBRESALA { get; set; }
        public int CAPACIDAD { get; set; }
        public int PISO { get; set; }
        public string EQUIPAMIENTO { get; set; }
        public bool POSEE_NOTE { get; set; }
        public bool POSEE_MONITOR { get; set; }
        public bool POSEE_VC { get; set; }
        public bool DISPONIBILIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA> RESERVA { get; set; }
        public virtual UBICACION UBICACION { get; set; }
    }
}
